before:
  hooks:
    - go mod download
    - go mod tidy
builds:
-
  id: metr-darwin
  env:
  - CGO_ENABLED=1
  goos:
    - darwin
  goarch:
    - amd64
  ldflags:
    - -s -w -X github.com/k1LoW/metr.version={{.Version}} -X github.com/k1LoW/metr.commit={{.FullCommit}} -X github.com/k1LoW/metr.date={{.Date}} -X github.com/k1LoW/metr/version.Version={{.Version}}
-
  id: metr-linux
  env:
  - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
  ldflags:
    - -s -w -X github.com/k1LoW/metr.version={{.Version}} -X github.com/k1LoW/metr.commit={{.FullCommit}} -X github.com/k1LoW/metr.date={{.Date}} -X github.com/k1LoW/metr/version.Version={{.Version}}
archives:
-
  id: metr-archive
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
    - goos: darwin
      format: zip
  files:
    - CREDITS
    - README.md
    - CHANGELOG.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  skip: true
brews:
-
  name: metr
  github:
    owner: k1LoW
    name: homebrew-tap
  commit_author:
    name: k1LoW
    email: k1lowxb@gmail.com
  homepage: https://github.com/k1LoW/metr
  description: 'metr gets system metrics.'
  install: |
    system './metr', 'completion', 'bash', '--out', 'metr.bash'
    system './metr', 'completion', 'zsh', '--out', 'metr.zsh'
    bin.install 'metr'
    bash_completion.install 'metr.bash' => 'metr'
    zsh_completion.install 'metr.zsh' => '_metr'
nfpms:
  -
    id: metr-nfpms
    name_template: "{{ .ProjectName }}_{{ .Version }}-1_{{ .Arch }}"
    builds:
    - metr-linux
    homepage: https://github.com/k1LoW/metr
    maintainer: Ken'ichiro Oyama <k1lowxb@gmail.com>
    description: "'metr' provides an easy way to use host/process metrics for shell script/monitoring tool."
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    epoch: 1
