before:
  hooks:
    - go mod download
    - go mod tidy
builds:
-
  id: metr-darwin
  env:
  - CGO_ENABLED=1
  goos:
    - darwin
  goarch:
    - amd64
  ldflags:
    - -s -w -X github.com/k1LoW/metr.version={{.Version}} -X github.com/k1LoW/metr.commit={{.FullCommit}} -X github.com/k1LoW/metr.date={{.Date}} -X github.com/k1LoW/metr/version.Version={{.Version}}
-
  id: metr-linux
  env:
  - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
  ldflags:
    - -s -w -X github.com/k1LoW/metr.version={{.Version}} -X github.com/k1LoW/metr.commit={{.FullCommit}} -X github.com/k1LoW/metr.date={{.Date}} -X github.com/k1LoW/metr/version.Version={{.Version}}
archives:
-
  id: metr-archive
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
    - goos: darwin
      format: zip
  files:
    - CREDITS
    - README.md
    - CHANGELOG.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  skip: true
brews:
-
  name: metr
  github:
    owner: k1LoW
    name: homebrew-tap
  commit_author:
    name: k1LoW
    email: k1lowxb@gmail.com
  homepage: https://github.com/k1LoW/metr
  description: 'metr.'
  install: bin.install 'metr'
