language: go
go:
  - 1.12.x
  - master
matrix:
  allow_failures:
    - go: master
env: GO111MODULE=on
install:
  - sudo pip install codecov
  - echo $TRAVIS_GO_VERSION
script:
  - make ci
after_script:
  - codecov

